image: node:14

clone:
  depth: full

definitions:
  steps:
    - step: &FormatLint
        name: check files format & lint
        script:
          - npm install
          - npm run format:check
          - npm run lint
    - step: &Build
        name: check Build
        script:
          - npm install
          - npm run build

pipelines:
  pull-requests:
    '**':
      - step: *FormatLint
      - step: *Build

  branches:
    master:
      - step: *FormatLint
      - step: *Build





